events {
    # Keeps default network settings open for handling active connection worker processes
    worker_connections 1024;
}

http {
    upstream node_backend {
        # Round-Robin load balancing over our isolated Docker container endpoints
        server node_app_1:3000;
        server node_app_2:3000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://node_backend;
            
            # WebSockets Upgrade Headers 👇
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}